### ISSUE TITLE
Error running gradlew clean build

### ISSUE THREAD

**Issue by lfatty** [vmware/burp-rest-api#1]
Hello there, thanks for the great work, however I got an error when trying to run and build. `Could not find or load main class org.gradle.wrapper.GradleWrapperMain`

**Comment by lfatty** [comment]
It seems like _gradle-wrapper.jar_ is missing.

**Comment by hshar7** [comment]
I am having same issue. Please can you provide information on how you got around this?
I'm not a java person so all this is new stuff to me.
Some are saying to use git add -f gradle/wrapper/gradle-wrapper.jar to get the jar file but that isn't doing anything since this repo doesn't have it.

**Comment by hshar7** [comment]
Instead of using gradle wrapper I was able to run this using regular gradle version < 3.0
On Macports I was able to get version 2.14 using commands:
$_ svn checkout -r 150408 https://svn.macports.org/repository/macports/trunk/dports/devel/gradle
$_ cd gradle
$_ sudo port install
:)

**Comment by dmettem** [comment]
Thanks for reporting. Added the gradle-wrapper.jar explicitly.

@lfatty @hshar7 Confirm if you are able to run the build with gradle wrapper.
