### ISSUE TITLE
Implementation of JAXB-API has not been found on module path or classpath.

### ISSUE THREAD

**Issue by sindhua25** [vmware/burp-rest-api#106]
I tried to access - /swagger-ui.html#/burp-controller/getProxyHistoryUsingGET after setting up rest-api jar. This works fine!
However, upon accessing /burp/proxy/history, seems to have an issue. 
Obtaining the below error, please suggest the needful to make it working.

There was an unexpected error (type=Internal Server Error, status=500).
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.http.converter.HttpMessageConversionException: Could not create JAXBContext for class [class com.vmware.burp.extension.domain.HttpMessageList]: Implementation of JAXB-API has not been found on module path or classpath.; nested exception is javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath. - with linked exception: [java.lang.ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory]

**Comment by tomaszdoyensec** [comment]
Hey @sindhua25, hope you resolved this problem, if not, can you share more details about your installation?

**Comment by ikkisoft** [comment]
Since the issue is stale, and verified that ```curl -X GET "http://localhost:8090/burp/proxy/history" -H "accept: */*"``` works on the latest release, I am closing this issue. In case of problems, please open a new issue with clear step-by-step instructions.
