### ISSUE TITLE
Cannot start BurpSuite because of Java springframework issue

### ISSUE THREAD

**Issue by IgorSasovets** [vmware/burp-rest-api#107]
**Describe the bug**
Hello team! I downloaded the [latest](https://github.com/vmware/burp-rest-api/releases/download/v2.1.0/burp-rest-api-2.1.0.jar) burp-rest-api precompiled jar file. Then, I ran the following command to start BurpSuite:
```
java -jar ~/Downloads/burp-rest-api-2.1.0.jar burp.jar=/home/user/BurpSuitePro/burpsuite_pro.jar
```
As a result, I received an error that Burp hadn't managed to start because of Java classNotFound exception. I attached a log file to this issue. 

**Expected behavior**
BurpSuite pro daemon started with the provided parameters

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.04
 - Burp Suite _Professional_ version: v2020_4
 - Extension **burp-rest-api** version: 2.1.0
 - Java version: openjdk, 11.0.5

**Additional context**
Error log: 
log file
[burp-error.log](https://github.com/vmware/burp-rest-api/files/4711314/burp-error.log)

**Comment by ikkisoft** [comment]
With newer JDKs, you have to use the wrapper: ./burp-rest-api.sh or ./burp-rest-api.bat

**Comment by IgorSasovets** [comment]
Closed, duplicate of https://github.com/vmware/burp-rest-api/issues/93

**Comment by IgorSasovets** [comment]
@ikkisoft , I received the same issue while using ./burp-rest-api.sh
```
./burp-rest-api.sh --burp.jar=/home/ubuntu/BurpSuitePro/burpsuite_pro.jar
```

**Comment by ikkisoft** [comment]
@tomaszdoyensec is taking a look. Thanks

**Comment by tomaszdoyensec** [comment]
Hey @IgorSasovets! Thank you for showing interest within the project. Unfortunately at this moment we do not support `burp.jar` param for JRE > 9, as the return value of `getSystemClassLoader()` is no longer an `URLClassLoader` object. To make it happen we should consider to create a new custom class loader that bypasses this situation by reflection, which is not planned at the moment. To make tool work properly with the JDK-11.0.5 I would suggest you to follow the readme, which states to put the burp-rest-api.sh, burpsuite_pro.jar and burp-rest-api.jar within the same directory and run .sh file.

**Comment by IgorSasovets** [comment]
Hello, @tomaszdoyensec ! Thank you for the quick response. I tried the suggested scenario but got another issue. Burp daemon unexpectedly shuts down after a couple of seconds from start. I downloaded the latest burp-rest-api [jar](https://github.com/vmware/burp-rest-api/releases/download/v2.1.0/burp-rest-api-2.1.0.jar) and [bash script](https://github.com/vmware/burp-rest-api/releases/download/v2.1.0/burp-rest-api.sh) and moved them into the folder with a burpsuite_pro.jar . Then, I used the below command to start BurpSuite (within the folder that contains all required files):
```
./burp-rest-api.sh --project-file=test-project.burp
```
Log file:
[error-log.log](https://github.com/vmware/burp-rest-api/files/4716147/error-log.log)

**Comment by tomaszdoyensec** [comment]
Hey @IgorSasovets, I was trying to replicate your problem and I've used the exact software (versions) you mentioned. Are you sure that the test-project.burp file is a valid one? 
Can you tell me what happens when you follow this approach:
1. Start Burp Suite Pro (windowed) and create a new project
2. Configure the project
3. Save and exit burp
4. Then place the `project_name.burp` file in the directory where the rest of files (`burpsuite_pro.jar`, `burp-rest-api-2.1.0.jar` and `burp-rest-api.sh`) are located
5. Finally run `./burp-rest-api.sh --project-file=project_name.burp` ?

**Comment by IgorSasovets** [comment]
Hi, @tomaszdoyensec ! I followed the mentioned scenario and received exactly the same error. After that, I decided to run `burp-rest-api` script with `--headless.mode=false` parameter in order to start BurpSuite in UI mode. Project closed after a few seconds from start but I received the following error:
![image](https://user-images.githubusercontent.com/27974884/83738393-efe22a00-a65c-11ea-9d92-d0b5a11f1a2e.png)

**Comment by IgorSasovets** [comment]
@tomaszdoyensec , @ikkisoft , I finally managed to start a BurpSuite using `burp-rest-api.sh` script.  Thank you for your time and help! Failures were caused by `headless-burp-proxy` [project](https://github.com/NetsOSS/headless-burp) jar files that were placed in the same folder. I think it should be mentioned in the README of this project because this issue can cause incorrect work of the project. Can I open a PR for it?

**Comment by ikkisoft** [comment]
Yes, please and thanks a lot to you!

**Comment by ikkisoft** [comment]
**Note for the future**: If there are JAR files of the [headless-burp-proxy](https://github.com/PortSwigger/headless-burp) project in the same folder with the original Burp Suite JAR, please move them to another location because they can cause the failures of `burp-rest-api.{sh,bat}` script.
