### ISSUE TITLE
Error: Bad Request on /burp/proxy/history , /burp/target/sitemap , /burp/scanner/issues

### ISSUE THREAD

**Issue by hardikrana437** [vmware/burp-rest-api#111]
Getting Error: Bad Request while retrieving the issues.
Note: I have populated sitemap through my rest-api framework proxy.
Same error I am getting while getting the sitemap.
Response body:

{
  "timestamp": "2020-06-25T05:37:41.198+0000",
  "status": 400,
  "error": "Bad Request",
  "message": "URLDecoder: Illegal hex characters in escape (%) pattern - Error at index 1 in: \"1$\"",
  "path": "/burp/scanner/issues"
}

1. curl -X GET "http://localhost:8090/burp/scanner/issues" -H "accept: */*"

**Expected behavior**
It should return all the issues in the issue activity

**Desktop (please complete the following information):**
 - OS: Windows
 - Burp Suite _Professional_ version: 2020.5

This issue I am not getting in case of scanning a website.
@ikkisoft @adracea  any idea?

**Comment by adracea** [comment]
@hardikrana437  best way to "debug" it is open up the same session file with the API running in UI mode and look for any issues containing odd symbols , these might be extension generated and in my experience they almost always were .

**Comment by hardikrana437** [comment]
@adracea in burp Ui I am not getting any error, and issues are getting generated successfully but while using /burp/scanner/issues api, the above error is getting generated.

**Comment by adracea** [comment]
Look closely at each issue , one of them surely contains an odd symbol . I know a savage breaker of APIs was the J2EE Scanner plugin that was reporting some protocol related issues .

**Comment by adracea** [comment]
If you can export them to xml and validate the xml using some validator that would be perfect .

**Comment by hardikrana437** [comment]
Not facing this issue with burp 1.7

**Comment by ikkisoft** [comment]
@hardikrana437 can you provide step by step repro using an online webpage? this would be the easier for us to reproduce and fix. Considering that you don't have this issue with burp 1.7, it's either a plugin or burp bug. Nevertheless, if we can reproduce locally we will investigate. Cheers!

**Comment by ikkisoft** [comment]
@hardikrana437 can you follow up on this one? If it's not an issue, we will close the ticket

**Comment by ikkisoft** [comment]
Stale issue. Closing it.
