### ISSUE TITLE
Scan configurations not taking from config file 

### ISSUE THREAD

**Issue by hardikrana437** [vmware/burp-rest-api#113]
**Describe the bug**
Scan and intercept configurations not taking from config file 

I want to add new resource pool config for my future scans and turn off the intercept

Below is my config file:

`
{

        "target":{
                "scope":{
                        "advanced_mode":false,
                        "exclude":[],
                        "include":[
                                {
                                        "enabled":true,
                                        "prefix":"http://localhost"
                                }
                        ]
                }
        },
        "scanner":{
                "active_scanning_engine":{
                        "concurrent_request_limit":20,
                        "do_throttle":true,
                        "follow_redirects":true,
                        "number_of_retries_on_failure":3,
                        "pause_before_retry_on_failure":2000,
                        "throttle_interval":500,
                        "throttle_random":false
                }}
,
"proxy":{
 "intercept_client_requests":{
            "automatically_fix_missing_or_superfluous_new_lines_at_end_of_request":false,
            "automatically_update_content_length_header_when_the_request_is_edited":true,
            "do_intercept":false,
            "rules":[
                {
                    "boolean_operator":"and",
                    "enabled":true,
                    "match_condition":"(^gif$|^jpg$|^png$|^css$|^js$|^ico$)",
                    "match_relationship":"does_not_match",
                    "match_type":"file_extension"
                },
                {
                    "boolean_operator":"or",
                    "enabled":false,
                    "match_relationship":"contains_parameters",
                    "match_type":"request"
                },
                {
                    "boolean_operator":"or",
                    "enabled":false,
                    "match_condition":"(get|post)",
                    "match_relationship":"does_not_match",
                    "match_type":"http_method"
                },
                {
                    "boolean_operator":"and",
                    "enabled":false,
                    "match_relationship":"is_in_target_scope",
                    "match_type":"url"
                }
            ]
        }
}
}

`

**Expected behavior**

New scans should be run with these new resource pool config and intercept should be off

@adracea @ikkisoft any comments?

**Comment by adracea** [comment]
In Burp UI under `User Options` -> `Misc` -> `Proxy Interception` -> `Enable Interception at Startup` save the *User* Options file and load it through the rest api using `--user-config-file=` .

**Comment by hardikrana437** [comment]
I tried this t @thing adracea but it came up with below exception

`
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'burpService' defined in URL [jar:file:burp-rest-api-master/b
urp-rest-api-master/burp-rest-api-2.1.0.jar!/BOOT-INF/classes!/com/vmware/burp/extension/service/BurpService.class]: Bean instantiation via constructor failed; nested excepti
on is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.vmware.burp.extension.service.BurpService]: Constructor threw exception; nested excepti
on is java.lang.NullPointerException

`

**Comment by hardikrana437** [comment]
Thanks @adracea ,it workerd. Can we set the  new resource pool config for my future scans?

Sometimes my scan got paused due to consecutive items got failed. I dont want it to get paused as it will hinder the process.

**Comment by adracea** [comment]
Not sure about the resource pool , I think that can be configured via a scan configuration which is saved in the scan config library but I'm not sure how that works in Burp itself . These are mostly burp suite configs and not related to API usage .

**Comment by hardikrana437** [comment]
@ikkisoft  I have loaded my  config file with foll configuration. I want to pause the task if 100 consecutive items to be paused. But after loading the file also, pause_task_failed_audit_item_count is getting set to 10.
"scanner":{
              
                "error_handling":{
                        "consecutive_audit_check_failures_to_skip_insertion_point":2,
                        "consecutive_insertion_point_failures_to_fail_audit_item":2,
                        "number_of_follow_up_passes":1,
                        "pause_task_failed_audit_item_count":100,
                        "pause_task_failed_audit_item_percentage":0
                }
        }

**Comment by hardikrana437** [comment]
@ikkisoft 
Unfortunately, we cannot currently set a default configuration for the scan in Burp Pro for all the scans.
We can have the scan config option while performing the scan where we can load config json for that particular scan.

So can we take this as feature?

**Comment by adracea** [comment]
@hardikrana437 I just took a quick look at burp's extender API and it doesn't really look like it sadly . I think they only expose this option via burp's own rest api when starting a scan . The downside of their own api is the fact that it can only do crawl and audit scans , ignoring all of the sitemap data provided by automated tests .

**Comment by hardikrana437** [comment]
@adracea so it's not possible to have this configure feature at scan level with this project?

**Comment by adracea** [comment]
@hardikrana437 Burp Suite doesn't expose Scanner 2.0 via the extender API , it used to be scanner configs were part of the Project Options and not a separate thing .

**Comment by adracea** [comment]
Also there is an option to load config files via the API which you could try to leverage . Like
`PUT Configs -> Start Scan -> Finish ->Put 2nd Configs -> Start 2nd Scan ...`

**Comment by hardikrana437** [comment]
@adracea  Yes I have tried that thing but it didn't work
My config file is :
`
{

        "target":{
                "scope":{
                        "advanced_mode":false,
                        "exclude":[],
                        "include":[
                                {
                                        "enabled":true,
                                        "prefix":"http://mysite.com"
                                }
                        ]
                }
        },
        "scanner":{
                "active_scanning_engine":{
                        "concurrent_request_limit":100,
                        "do_throttle":false,
                        "follow_redirects":true,
                        "number_of_retries_on_failure":3,
                        "pause_before_retry_on_failure":2000,
                        "throttle_interval":500,
                        "throttle_random":false
                },
                "audit_optimization":{
                        "consolidate_passive_issues":true,
                        "follow_redirections":true,
                        "maintain_session":true,
                        "scan_accuracy":"normal",
                        "scan_speed":"normal",
                        "skip_ineffective_checks":true
                },
                "error_handling":{
                        "consecutive_audit_check_failures_to_skip_insertion_point":2,
                        "consecutive_insertion_point_failures_to_fail_audit_item":2,
                        "number_of_follow_up_passes":1,
                        "pause_task_failed_audit_item_count":100,
                        "pause_task_failed_audit_item_percentage":0
                }
        }
}
`

The scope is getting set with the url but when I went to burp UI and has naviagted to scan's configuration, the default configs are there instead of new one.(i.e pause_task_failed_audit_item_count is set with value 10 which is default one).

**Comment by adracea** [comment]
@hardikrana437 If this is the case...could you try using the rest api with a burp 1.7.X jar ? That might solve your issue here I guess

**Comment by hardikrana437** [comment]
@adracea Unfortunately, I have only Burp version 2020.5 jar with me. Has this project needs to be updated to deal with that?

**Comment by hardikrana437** [comment]
Plus is there any way @adracea that we can get the status of scan whether its running, paused or finished and if it is paused we can resume it after particular duration.

**Comment by adracea** [comment]
You can download older jar files from portswigger . Sadly the extender is not exposing such a thing , we can get the status and number of errors but we can't pause/resume a scan , we can only remove it/cancel it . The project currently works with everything that burp exposes through the extender , the fact that Burp doesn't expose extender API details for scanner 2.0 is an understandable probably intentional lapse on the developer's side since they now provide the "Enterprise" edition as well .

**Comment by hardikrana437** [comment]
@adracea I tried with burp 1.7 with --headless.mode=false. I observed in scan queue tab all the tasks are has waiting status and there is Paused status at the botton. Plus there is no error_handling option in burp 1.7. However if I resume by double clicking on Pause, scan is getting started.
Can you tell the reason why scan is getting paused as there is no reason in event log.

Then I tried with headless mode and trigger the scan by /burp/scanner/scans/active. It is giving me the correct scan percentage but after few minutes when I am retrieving the scan status, /burp/scanner/status api is trying to fetch percentage but not coming out of loop. After some time it is throwing the error: Not able to fetch the response.
