### ISSUE TITLE
Not able to retrieve scan status with Burp version 1.7

### ISSUE THREAD

**Issue by hardikrana437** [vmware/burp-rest-api#114]
**Describe the bug**
Not able to retrieve scan status with Burp version 1.7

**To Reproduce**
1. Initialise burp using ./burp-rest-api.sh 
2. include a url in scope
3. trigger a scan
4. retrieve scan status again and again till 100% is achieved

code for checking this:
`
     
     String responseText="";

     int responseCode=200;

    while(!responseText.equalsIgnoreCase("100") && responseCode==200)

    {

        System.out.print(responseText+"true");

        URL urlForGetRequest = new URL("http://localhost:8090/burp/scanner/status");
       
         String readLine = null;

        HttpURLConnection conection = (HttpURLConnection) urlForGetRequest.openConnection();

        conection.setRequestMethod("GET");

        responseCode = conection.getResponseCode();

        System.out.println("response"+responseCode);

            BufferedReader in = new BufferedReader(

                    new InputStreamReader(conection.getInputStream()));

            String response = "";

            while ((readLine = in .readLine()) != null) {

                response+=(readLine);

            } in .close();
        JSONObject jsonObj = new JSONObject(response);
            // print result
    responseText= String.valueOf(jsonObj.get("scanPercentage"));
            System.out.println("ScanPercentage",responseText);
        TimeUnit.MINUTES.sleep(2);
            //GetAndPost.POSTRequest(response.toString());

    }

`
O/P I got :

response 200
ScanPercentage 0
response200
ScanPercentage 4
response200
ScanPercentage 14
response200
ScanPercentage 17

and after this code doesnt return anything

**Expected behavior**
It should return scan status

**Desktop (please complete the following information):**
 - OS:  Windows
 - Burp Suite _Professional_ version: 1.7
 - Extension **burp-rest-api** version  latest

Note: I perform get request from  swagger UI to get scan status but its showing loading again and again, finally after 10 mins it gave 1 error. i.e TypeError: Failed to fetch

@ikkisoft @adracea

**Comment by hardikrana437** [comment]
I have noticed there is no problem with above code but it is with the way I am initialising the burp

`
 
    ProcessBuilder builder2 = new ProcessBuilder(
            "cmd.exe", "/c", "cd \"C:\\burp-rest-api-master\" && burp-rest-api.bat --headless.mode=false");
    builder2.redirectErrorStream(true);
    Process p3 = builder2.start();
    BufferedReader r2 = new BufferedReader(new InputStreamReader(p3.getInputStream()));
    String line2;
    ArrayList a=new ArrayList();
    line2 = r2.readLine();
    p3.waitFor(25,TimeUnit.SECONDS);

    while (true) {

        System.out.print("done");

        line2 = r2.readLine();
        if (line2 == null) { break; }
        
    }
`

As soon as I am entering to the while loop, and if we try to hit the api (get scan) again and again multiple times, api is getting crashed. Any idea  @adracea ?

**Comment by adracea** [comment]
Have you tried manually starting the api in the console with `burp-rest-api.bat --headless.mode=false` and then getting the status with the first script to see if there's any errors from the API ?
The additional wrapper script you're using seems a bit overkill ?

**Comment by hardikrana437** [comment]
No @adracea  I am not getting any error  starting the api in the console with burp-rest-api.bat --headless.mode=false and then getting the status with the first script.
The additional wrapper script is creating the problem only but does not know the exact reason behind it. Is this the api problem>

**Comment by adracea** [comment]
Well , by the looks of it , it's related to your wrapper script as , if it were a problem with the api , it would replicated when directly starting it and using the script .

**Comment by hardikrana437** [comment]
Can you suggest any way out here as I want to run my burp, fill the sitemap through proxy and then scan in single java code.

**Comment by ikkisoft** [comment]
Since this doesn't look like a bug in the rest-api component, closing the issue.
