### ISSUE TITLE
Scan status not getting extracted

### ISSUE THREAD

**Issue by hardikrana437** [vmware/burp-rest-api#117]
Scan status is not getting extracted for a particular scan (whether it is paused). If my scan got paused due to consecutive audit failures, the scan keeps on running and scan percentage got stuck.

**Expected behavior**
It should return the status of the scan if it got paused and an option to resume it or cancel the scan.

**Desktop (please complete the following information):**
 - OS: Windows
 - Burp Suite _Professional_ version: 2020.7
 - Extension **burp-rest-api** version :latest

**Comment by hardikrana437** [comment]
@ikkisoft @adracea any idea on this?

**Comment by ikkisoft** [comment]
As far as I remember the status % of the scan is implemented as a binary 0 (work in progress) or 100% finished since Burp APIs in v2.x removed the ability to see the actual % progress. Unfortunately, I don't have the bandwidth to look into this at the moment.

**Comment by hardikrana437** [comment]
Burp native api gives the option to see the scan status I think whether it is in progress or paused. Something like that would be great.

**Comment by ikkisoft** [comment]
I don't believe this is exposed by the extender API - https://portswigger.net/burp/extender/api/

**Comment by hardikrana437** [comment]
IScanQueueItem.getStatus() will not work @ikkisoft ??

**Comment by ikkisoft** [comment]
That API is deprecated, and doesn't provide details on pause/running.

**Comment by hardikrana437** [comment]
At https://portswigger.net/burp/extender/api/deprecated-list.html, I can find burp.IScanQueueItem.getPercentageComplete() as deprecated,not IScanQueueItem.getStatus()

**Comment by ikkisoft** [comment]
Actually, looks like you're right...I missed that. We can certainly expose `getStatus()`. Yet, we cannot provide any ETA at the moment.

**Comment by hardikrana437** [comment]
Sure @MohmedH.

**Comment by MohmedH** [comment]
@hardikrana437 Check the recent PR I submitted. This will expose scan status. Not sure how this compares to the current percentage, but if you are running only one scan and checking the status of it, this will do the job

**Comment by ikkisoft** [comment]
We've just merged this change in master, and we will be probably making a new release in a month or so.

**Comment by byposeidon** [comment]
> We've just merged this change in master, and we will be probably making a new release in a month or so.

Hi Luca, is there any progress on this issue?

**Comment by ikkisoft** [comment]
It's in master, so you can pull that down and compile the extension if you want.

In term of an official release, it will happen in the May/June timeframe.

**Comment by byposeidon** [comment]
Hi Luca,

Why is progress not progressing?
1.7.37 version is progressing normally. But in all later versions the progress doesn't work.

The result is always the same: **scanPercentage: 0**
Terminal response: Getting Scanner percentage complete. (Always the same result until 1 hour after the scan started)
