### ISSUE TITLE
update/add dependency management plugin release version in build.gradle

### ISSUE THREAD

**Issue by ryanbreed** [vmware/burp-rest-api#12]
building with spring-boot-gradle-plugin 1.3.2 bombs out with an error: "Could not create task of type 'DependencyManagementReportTask'."

    FAILURE: Build failed with an exception.
    * Where:
    Build file 'burp-rest-api/build.gradle' line: 15
    * What went wrong:
    A problem occurred evaluating root project 'burp-rest-api'.
    > Failed to apply plugin [class 'io.spring.gradle.dependencymanagement.DependencyManagementPlugin']
    > Could not create task of type 'DependencyManagementReportTask'.

Seems to be related to this known [issue](https://discuss.gradle.org/t/3-0-m1-springboot-1-3-5-project-fails-to-build-aborts-with-an-error-message-on-creation-of-dependencymanagementreporttask/17999/5)

quick [fix is to add updated dependency management plugin](https://discuss.gradle.org/t/3-0-m1-springboot-1-3-5-project-fails-to-build-aborts-with-an-error-message-on-creation-of-dependencymanagementreporttask/17999/6) to the dependencies section of the buildscript.

```
15:46 $ gradle --version

------------------------------------------------------------
Gradle 3.4.1
------------------------------------------------------------

Build time:   2017-03-03 19:45:41 UTC
Revision:     9eb76efdd3d034dc506c719dac2955efb5ff9a93

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_112 (Oracle Corporation 25.112-b16)
OS:           Mac OS X 10.12.3 x86_64
```

this worked for me:
```
15:53 $ git diff build.gradle
diff --git a/build.gradle b/build.gradle
index def410c..3d044f4 100644
--- a/build.gradle
+++ b/build.gradle
@@ -5,6 +5,7 @@ buildscript {
     }

     dependencies {
+        classpath("io.spring.gradle:dependency-management-plugin:0.6.1.RELEASE")
         classpath("org.springframework.boot:spring-boot-gradle-plugin:1.3.2.RELEASE")
     }
 }
```

I don't know enough about gradle/spring boot to submit a more refined fix (if any is actually needed), so no offense taken if you close this wontfix straight away

**Comment by vkalal** [comment]
@ryanbreed does it work without plugin for you, just by installing gradle.

**Comment by ryanbreed** [comment]
@vkalal ah, i see - i thought i was starting out with a vanilla gradle install. I'll re-run the build and try to make sure spring-boot-gradle-plugin is not in the mix. I'll close this issue out and open a different one if that build fails.
