### ISSUE TITLE
Compatibility with burp 2020.11

### ISSUE THREAD

**Issue by gauravshet86** [vmware/burp-rest-api#120]
I am facing issues running it with latest version of burp pro 2020.11

**Comment by dpnishant** [comment]
Hi,

What changes is required to make use this project with Burp Suite Pro 2020.xx.xx given that the new Burp Suite Pro requires Java 13 or higher. Will recompiling the source with a supported version of Java e.g. 15 be enough or a code/dependency upgrade might be required?

**Comment by tomaszdoyensec** [comment]
> I am facing issues running it with latest version of burp pro 2020.11

Hey @gauravshet86, can you provide more details?
I've tried running the tool with the following:
1. Java SE 14
2. Burp Professional 2020.11.3

And haven't noticed problems with this configuration.

**Comment by ikkisoft** [comment]
@dpnishant any update on this one? can we close it?

**Comment by dpnishant** [comment]
@ikkisoft There is no further action expected on this and can be closed.
