### ISSUE TITLE
Question: First scan guidelines

### ISSUE THREAD

**Issue by akordzik** [vmware/burp-rest-api#123]
Hey guys,

thanks for keeping up with good work. I just tried running API for the first time and it all works as a charm.
The only problem I encounter is actually running a first scan. After I invoke an endpoint I get error response:

```
{
  "timestamp": "2021-03-22T18:12:59.079+0000",
  "status": 409,
  "error": "Conflict",
  "message": "The 'baseUrl' is NOT in scope. Set the 'baseUrl' scope to true before retry.",
  "path": "/burp/scanner/scans/active"
}
```

and TBH I have no idea what to do with it (tried to search through closed issues, but couldn't get any tangible response).

I tried trial and error approach with amending configuration (`POST` or `PUT` endpoints), and tried adding URL to `Scope` but it didn't help.

**Comment by ikkisoft** [comment]
Hey Artur,

You just need to add the target URL in scope (as you would normally do in Burp) using the specific API.

Thanks,
Luca

**Comment by akordzik** [comment]
Hey @ikkisoft ,

thanks for the hint. So I added that URL as target URL and I'm no longer getting that error. 

Though when I try to run active scan I'm getting no result and console output tells me:
`Number of URLs submitting for Active/Passive Scan: 0`
So then I tried running a Spider scan, but it seems to be stuck as it's been 2 hours already. When I invoke `/burp/spider/status` I keep getting response:
```
{
  "spiderPercentage": 0
}
```

Any clues?

**Comment by tristanlatr** [comment]
Hi @akordzik,

I've been writing a Python client for the `burp-rest-api`: [`burpa`](https://github.com/tristanlatr/burpa), please feel free to use it.

The CLI uses both the official Burp REST API and the `burp-rest-api` extension, but you can directly use the underlying object: [`BurpRestApiClient`](https://tristanlatr.github.io/burpa/burpa.BurpRestApiClient.html).

See methods `BurpRestApiClient.active_scan`, `BurpRestApiClient.scan_status ` and `BurpRestApiClient.scan_report `
