### ISSUE TITLE
Burp ask me for activation for systemctl when it was already activated for my linux user. 

### ISSUE THREAD

**Issue by alex4561** [vmware/burp-rest-api#124]
I create a daemon via systemctl to run burp-rest-api, but when I make **systemctl start daemon.service** and check it status, i see, that a Burp ask me for activation when it was already activated for my linux user. What I do wrong?..

Config:

**[Unit]
Description=Burp RestAPI Service
[Service]
Type=simple
ExecStart=/usr/local/BurpRest/burp-rest-api.sh
Restart=on-failure
[Socket]
ListenStream=--host--:--port--
Accept=yes
[Install]
WantedBy=default.target**

I could not map https://github.com/vmware/burp-rest-api/blob/master/FAQ.md to my situation. I have ~/.java/.userPrefs/burp/prefs.xml but it not works. Or this question for guys from PortSwiger?..

**Comment by ikkisoft** [comment]
This daemon is probably executing as _root_. As such, that user doesn't have the license file.
