### ISSUE TITLE
Add support for multiple urlPrefix when using `/burp/report` API

### ISSUE THREAD

**Issue by tristanlatr** [vmware/burp-rest-api#126]
It would be very useful to be able to report on a collection of `urlPefix` when using `/burp/report` API. 

When having a very hight number of websites, this feature would be very valuable. 

In the mean time, we can always start the `burp-rest-api` executable with options `--headless=false --unpause-spider-and-scanner`, start bunch of scans with the API, and generate the report manually from GUI by selecting everything.

If you think the implementation of such feature is not too complicated, I would try to mobilize my old Java skills and give it a go. But it's been a while!

Thanks for your feedback.

**Comment by ikkisoft** [comment]
Closing this one since I am consolidating all reporting enhancements in https://github.com/vmware/burp-rest-api/issues/125
