### ISSUE TITLE
Burp scanner is in waiting state for all URLS

### ISSUE THREAD

**Issue by lsuto** [vmware/burp-rest-api#13]
1. Start SPIDER on

curl -X POST --header 'Content-Type: application/json' --header 'Accept: */*' 'http://yyy.yyy.yyy.yyy:8090/burp/spider?baseUrl=https://xxx.xxx.xxx.xxx'

1. Add Target Scope

curl -X PUT --header 'Content-Type: application/json' --header 'Accept: */*' 'http:// yyy.yyy.yyy.yyy:8090/burp/target/scope?url=https://xxx.xxx.xxx.xxx'

1. Start Scan

curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' 'http:// yyy.yyy.yyy.yyy:8090/burp/scanner/scans/active?baseUrl=https://xxx.xxx.xxx.xxx'
<After this when I look BURP UI , under scanner tab , it shows "waiting" for all the URL's>

1. Get Status

curl -X GET --header 'Accept: application/json' 'http://10.142.147.30:8090/burp/scanner/status'

1. Generate Report

curl -X GET --header 'Accept: application/octet-stream' 'http:// yyy.yyy.yyy.yyy:8090/burp/report?urlPrefix=https://xxx.xxx.xxx.xxx&reportType=HTML'

WHERE:
xxx.xxx.xxx.xxx == Application IP where scan need to be performed
yyy.yyy.yyy.yyy == IP where BURP tool is running

BURP Jar ==> burpsuite_pro_v1.7.11.jar
VMWare REST API's for BURP --> burp-rest-api-1.0.0.jar

Issue:

1. Point#3 listed above, scan is showing in waiting state
2. Password for the App hosted on xxx.xxx.xxx.xxx is getting changed. For example: there is one user "onprem_nce" with password "xxxxxx". After BURP scan, we are not able to login to the application with "onprem_nce" user.?

**Comment by act1on3** [comment]
I have this issue too.
BURP Jar ==> burpsuite_pro_v1.7.23.jar

**Comment by vkalal** [comment]
@act1on3 @lsuto are you running it in UI mode or headless mode?

**Comment by lsuto** [comment]
I heard it needs to be in headless mode.

**Comment by vkalal** [comment]
I have tried with burpsuite_pro_v1.7.03.jar and it is working fine. You can unblock yourself by running it on burpsuite_pro_v1.7.03.jar meanwhile we will look into the issue.

**Comment by act1on3** [comment]
@lsuto yeah, it work in headless mode, without UI!
@vkalal burpsuite_pro_v1.7.23.jar also working.
Thanks

**Comment by vkalal** [comment]
closing the issues, as its working with burpsuite_pro_v1.7.23.jar. Feel free to reopen it.
