### ISSUE TITLE
Error creating bean with name 'burpService'

### ISSUE THREAD

**Issue by byposeidon** [vmware/burp-rest-api#133]
java -jar burp-rest-api-2.1.0.jar --headless.mode=false --burp.jar=./lib/burpsuite_pro.jar

Error creating bean with name 'appConfig'

WARN 22121 --- [main] org.eclipse.jetty.webapp.WebAppContext   : Failed startup of context o.s.b.w.e.j.JettyEmbeddedWebAppContext@75329a49{application,/,[file:///tmp/jetty-docbase.6171811323386930437.8090/, jar:file:/opt/burp-rest-api/build/libs/burp-rest-api-2.1.0.jar!/BOOT-INF/lib/springfox-swagger-ui-2.8.0.jar!/META-INF/resources],UNAVAILABLE}

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'appConfig': Unsatisfied dependency expressed through field 'service'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'burpService': Lookup method resolution failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [com.vmware.burp.extension.service.BurpService] from ClassLoader [org.springframework.boot.loader.LaunchedURLClassLoader@21b8d17c]

**Comment by ikkisoft** [comment]
On newer versions of Java, you have to use the launcher script

`./burp-rest-api.sh --headless.mode=false`

**Comment by byposeidon** [comment]
Hello @ikkisoft,
Thank you for your interest. I get the following error;

./burp-rest-api.sh --headless.mode=false

Unrecognized command-line argument: --headless.mode
Could not start Burp: java.awt.AWTError: Can't connect to X11 window server using ':0.0' as the value of the DISPLAY variable.

**Comment by ikkisoft** [comment]
The `Unrecognized command-line argument` is actually just a warning from Burp itself.

Execute with `./burp-rest-api.sh --headless.mode=true` and you will see that it's working.

You're getting the X11 error since you're probably running that from a server with no X running. Try to either use `export DISPLAY=:0` or `unset DISPLAY`
