### ISSUE TITLE
Unable to run use the JAR and Bash Script

### ISSUE THREAD

**Issue by omkark007** [vmware/burp-rest-api#134]
Hi, I have been trying to use the burp-rest-api.jar file and the bash script on ubuntu linux (20.04 LTS). However, the script and burp-rest-api JAR is failing on startup. 

I followed all the steps on fresh ubuntu linux and using different JAVA versions (JDK-8, JDK-14 and JDK-17). Also, I have tried to build the source using gradle as mentioned in the Readme file but still it is failing.

Can somebody please help me here. I have spent lot of time troubleshooting this but no success. I will really appreciate if you could respond as early as possible. I have attached the logs.

Thanks.

[burp-rest-api-startup-failed-logs.txt](https://github.com/vmware/burp-rest-api/files/8205325/burp-rest-api-startup-failed-logs.txt)

**Comment by ikkisoft** [comment]
The script includes this command 

`java -jar build/libs/burp-rest-api-2.1.0.jar --burp.jar=lib/burpsuite_pro.jar`

Have you tried using the latest .sh script currently on Master?

Please fill out the detailed https://github.com/vmware/burp-rest-api/issues/new?assignees=&labels=&template=bug_report.md

**Comment by omkark007** [comment]
Thanks! I have tried with the latest .sh script present on master and it worked! 

I guess earlier I was trying .sh script which I have downloaded from the latest release on the Releases page.
