### ISSUE TITLE
Is there any way to update cookie jar using REST API?

### ISSUE THREAD

**Issue by omkark007** [vmware/burp-rest-api#138]
To automate burp suite active scanning process, we are using your rest-api extension. However, in our use case, we have to update the cookies in the cookie jar via REST API. I dont think it is possible using the currently provided APIs. 

Is there any way where we can update the cookies in each and every HTTP request of proxy history using REST API? I have tried with Burp Macro but it is not working as expected.

Thanks.

**Comment by ikkisoft** [comment]
The BurpExtender API seems to provide this method

```
void	updateCookieJar(ICookie cookie)
This method is used to update the contents of Burp's session handling cookie jar.
```

so it's a matter of trying implementing the endpoint. We will do it.

**Comment by ikkisoft** [comment]
This is merged, and available in master!

**Comment by omkark007** [comment]
Thanks. I will check it out.
