### ISSUE TITLE
Unable to Get Scan Status

### ISSUE THREAD

**Issue by choua013** [vmware/burp-rest-api#140]
Hi,
I've successfully set this API up on my machine have created a jenkins job that allows me to add a URL to scope and then run an active scan on it. I've also created a groovy script that will loop until the status of the scan shows as complete (i.e. 100). For this, I'm using http://[IP_ADDRESS]:[PORT]/burp/scanner/status and once the status shows as complete, the request to retrieve the report is sent.
This wasn't working and I thought this was due to my script, but I then tried to execute this request through the Swagger UI as well as Postman, but I was getting the same results. 
The 'scan percentage' is always 0, even when I can see in Burp Suite that the Audit has completed (or it's been in progress for a while).
Not sure what's going on here, any help would be much appreciated.

**Comment by tristanlatr** [comment]
FYI, You can use the official Burp Rest API for that.

**Comment by vinilnarayan** [comment]
Hi @tristanlatr and @choua013,

Greetings!

I'm also stuck in the same situation. I always getting scanPercentage as '0' with _curl -X GET "[http://localhost:8090/burp/scanner/status"](http://localhost:8090/burp/scanner/status%22) -H "accept: */*"_.

I think the Burp Rest API comes with only Burp enterprise edition.
I'm using Burp pro version with vmware's burp-rest-api v2.1.0. And this cannot work with Burp enterprise edition.
Please correct me if i'm wrong.

Is there any other alternate work around to get scan status in Burp pro version with vmware's burp-rest-api v2.1.0 ?

**Comment by tristanlatr** [comment]
The Burp suite REST API is available to the pro version I believe. (The entreprise version includes some SAAS management platform)

I’d suggest you to use [burpa](https://github.com/tristanlatr/burpa), a high level python client for burp suite APIs. Burpa will use both official API to launch the scan and this extension API to generate the html report.

**Comment by ikkisoft** [comment]
This issue is fixed in master.

**Comment by vinilnarayan** [comment]
Hi @ikkisoft 
Thanks a lot for the fix!
