### ISSUE TITLE
Windows server 2019 - The supplied licence key was not recognized

### ISSUE THREAD

**Issue by ganesh2183** [vmware/burp-rest-api#143]
OS: Windows server 2019
I'm using Burp suite professional version, when I try to open burp using burp command line it is working fine without any issues. Also i have activated license for burp professional using GUI mode.

When I try to burp using VMware burp rest api, it is asking for license key, when i provide correct license key it is saying as 'The supplied licence key was not recognized. Please try re-entering your license key'.

Kindly help to resolve this issue.

**Comment by ikkisoft** [comment]
The mismatch in licenses seems to suggest that you're running the full bundle with a different user. [burp-rest-api](https://github.com/vmware/burp-rest-api) doesn't change the way licensing work so it's definitely an issue with the execution

**Comment by ikkisoft** [comment]
If you still think it's an error in this project, please open an **Issue: Bug report** with all required details
