### ISSUE TITLE
Persisting extension settings

### ISSUE THREAD

**Issue by v-p-b** [vmware/burp-rest-api#150]
I'm not sure if this is a problem with burp-rest-api, so take this more as a question:

Extensions can save configuration settings using the IBurpExtenderCallbacks.saveExtensionSetting() API. After using burp-rest-api, I noticed, that extension settings get "stuck", and can't be overridden. 

For example:
- I load [Piper](https://github.com/silentsignal/burp-piper/) with its default configuriation along with burp-rest-api, then shut down burp-rest-api
- I _rebuild_ the jar, so it'll contain a new default configuration, with only a single, new item
- I start burp-rest API again
- Piper settings contain both the default and modified configuration (incorrect behavior, it should only contain the new item)
- While running, I manually remove and add the Piper plugin in Burp GUI again
- Piper settings now contain only the new item as expected
- Restart burp-rest-api
- Piper settings contain both the default and modified configuration (incorrect behavior, it should only contain the new item)

I have problems with other extensions too (e.g. Hackvertor) , but the case of Piper is the most straightforward.

I see that extension preferences are stored under `~/.java/` in encrypted form, probably because of license management, which might be the culprit.

Have you observed similar behavior? Any ideas how to clean up extension settings?

__EDIT__ The only solution I could find is to change the name of the setting in Piper, which resolved the problem, but this is not and acceptable solution if extension preferences can change frequently.

**Comment by ikkisoft** [comment]
Thanks for the follow-up. Extensions here are tricky due to the way we inject the burp-rest-api extension itself.

I meant to check it, but didn't manage. Happy you figured it out.
