### ISSUE TITLE
Getting '400-Bad Request' response with '/burp/proxy/history'

### ISSUE THREAD

**Issue by vinilnarayan** [vmware/burp-rest-api#151]
**Describe the bug**
We have received many requests in history. But I'm getting 400 error response when I tried to get the list with 'burp/proxy/history'.

**Request**
_curl -X GET "http://localhost:8090/burp/proxy/history" -H  "accept: */*"_

**Error Response**
_{
  "timestamp": "2022-06-22T11:50:45.378+0000",
  "status": 400,
  "error": "Bad Request",
  "message": "URLDecoder: Incomplete trailing escape (%) pattern",
  "path": "/burp/proxy/history"
}_

**Additional data**
Application URL : [http://k8s-nginxing-nginxica-25d2d0087f-767d5dd7dff37e31.elb.ap-south-1.amazonaws.com/](http://k4s-nginxing-nginxica-45c2d4487g-734d5ff7dfg27e31.elb.ap-south-2.amazonaws.com/testapplication/app/main/#/home)

**Comment by ikkisoft** [comment]
In order to reproduce this issue we would either need a URL that we can test ourself (the "Application URL" provided is not reachable) or a Burp State with the Proxy history generating such error. Thanks!

**Comment by vinilnarayan** [comment]
Hi @ikkisoft ,

Yes, the application hosted internally which we cannot able to access without VPN.
Let me check and provide you more details.

**Comment by ikkisoft** [comment]
Given no ability to reproduce the problem, I am closing this issue. Feel free to re-open it when you have clear reproduction steps for us to triage the bug (if any).
