### ISSUE TITLE
Burp is not starting with burp-rest-api.sh via Jenkins

### ISSUE THREAD

**Issue by vinilnarayan** [vmware/burp-rest-api#153]
**Describe the bug**
I have created a Free style job in my Jenkins which I hosted in the same machine where I put Burp pro and burp-rest-api. In that Jenkins job, I do execute shell command like below.

_sh <path_to_burpRestAPI>/burp-rest-api.sh --headless.mode=true_

And not starting my burp and APIs. But i am able to start burp and APIs from CLI with the same shell command.

**Comment by vinilnarayan** [comment]
![Issue](https://user-images.githubusercontent.com/46709848/176352702-019f4426-3c23-4745-9261-f6758fd48c4a.jpg)

Please find the attached screenshot for the error.

**Comment by ikkisoft** [comment]
I assume this is similar to the other issue opened. This is caused by a Java version mismatch.
