### ISSUE TITLE
Include in Scope - no complex url handled

### ISSUE THREAD

**Issue by Arkango** [vmware/burp-rest-api#157]
Hello, I started using this automation few days ago.

When I try to add url in scope like: https://example.com/ the scan is correctly performed and burp returns issues.

But if I try to add a url like https://example.com:443/ no issues are returned.
The expected behaviour is which a url with port is handled as advanced scope management. 

What I'm missing? Or there is a bug?

Regards, Arcangelo.

**Comment by ikkisoft** [comment]
This issue should be fixed in master. It would be great if you could compile the extension from master and do a bit of testing. Thanks!
