### ISSUE TITLE
Custom config file not properly running with the api script

### ISSUE THREAD

**Issue by phoenixml** [vmware/burp-rest-api#159]
Hi All,

Kudos to this project and to these great efforts,
I am running burp-suite-api.sh  --config-file=custom.json --user-config-file=user.json

My custom.json file:
![image](https://user-images.githubusercontent.com/14360476/198827310-b5c1f66e-1bac-4abb-812a-83350fd4c025.png)

however the scan that I am getting is fast while in the custom.json config file I set the crawler to most complete and deep. I test it on burp gui and it is working as I am expected however the  scan from the cli is returning a fast / default results
 
Any idea what I am missing? 

Thank you :)

**Comment by iamsharan** [comment]
hey, I am getting "The supplied license key was not recognized. Please try re-entering your license key." error. Did you came across anything like this during your configuration.

**Comment by ikkisoft** [comment]
Please see https://github.com/vmware/burp-rest-api#burp-suite-support-and-limitations. Unfortunately we cannot control this. 

To confirm the issue, would you mind trying with an old Burp Suite Professional v1.7 version? It should work with no problems

**Comment by AlessandroCotto** [comment]
Hi, this screenshot highlights the differences between the config files. The `crawler` is inside the `spider` object which is not present in the latest version of the config file.
<img width="832" alt="Burp2022_vsBurp1_7" src="https://user-images.githubusercontent.com/5954741/204019292-29413a24-011e-45f4-b8fb-7b533c9b2059.png">

**Comment by phoenixml** [comment]
> Please see https://github.com/vmware/burp-rest-api#burp-suite-support-and-limitations. Unfortunately we cannot control this.
> 
> To confirm the issue, would you mind trying with an old Burp Suite Professional v1.7 version? It should work with no problems

Thank you heaps will do that cheers

**Comment by phoenixml** [comment]
> Hi, this screenshot highlights the differences between the config files. The `crawler` is inside the `spider` object which is not present in the latest version of the config file. <img alt="Burp2022_vsBurp1_7" width="832" src="https://user-images.githubusercontent.com/5954741/204019292-29413a24-011e-45f4-b8fb-7b533c9b2059.png">

Very helpful thank you.
