### ISSUE TITLE
Crash with latest Burp Suite v2022.12.6

### ISSUE THREAD

**Issue by tristanlatr** [vmware/burp-rest-api#165]
**Describe the bug**
Crash with Burp Suite v2022.12.6

**To Reproduce**
1. Try to run burp-rest-api 2.2.0 with Burp Suite _Professional_  v2022.12.6, it crashes

**Expected behavior**
It should work as normally. 

**Error log**
```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'appConfig': Unsatisfied dependency expressed through field 'service'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'burpService': Lookup method resolution failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [com.vmware.burp.extension.service.BurpService] from ClassLoader [org.springframework.boot.loader.LaunchedURLClassLoader@4459eb14]
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Burp Suite _Professional_ v2022.12.6
 - Extension **burp-rest-api** 2.2.0 

**Additional context**
It was working before the upgrade to v2.2022.12.6.

**Comment by ikkisoft** [comment]
Are you using the JAR downloaded from the Portswigger website (and not simply copying the one after installation)?

**Comment by ikkisoft** [comment]
They're now packaging Burp Suite in a different way

**Comment by mehakt99** [comment]
I have tried using version 22.9 of Burp along with burp-rest-api-2.2.0.jar, the jar is still crashing its not getting started
