### ISSUE TITLE
How i can start Burp Scanner ?

### ISSUE THREAD

**Issue by hhai98** [vmware/burp-rest-api#169]
1. I start with --project-file=/app/MyFile.burp
2. I call api  /scanner/scans/active?baseUrl=myapi
I check the curl -X GET "http://127.0.0.1:8090/burp/scanner/status/details" and just waiting, not scanning
{"scans":[{"url":"https://myhost/api/v1/xxx","status":"waiting"}]}
Can you guy help me how to start the scanner please !
Thanks

**Comment by Himan10** [comment]
Hey @hhai98, I am facing the same problem as you, how did you resolve it ?
