### ISSUE TITLE
 javax.net.ssl.SSLHandshakeException at BurpClientIT.java

### ISSUE THREAD

**Issue by ghost** [vmware/burp-rest-api#18]
I am facing issue  javax.net.ssl.SSLHandshakeException at BurpClientIT.java.Can any1 help me with this?

**Comment by Siddhant3108** [comment]
![sslerror](https://user-images.githubusercontent.com/30649987/28862254-ff20ab2a-7781-11e7-9dc4-3a621493e661.JPG)

**Comment by Siddhant3108** [comment]
![sslerror2](https://user-images.githubusercontent.com/30649987/28862285-247fecaa-7782-11e7-86d2-10f2b681422c.JPG)

**Comment by vkalal** [comment]
I am unable to reproduce this issue, how are you launching burp jar? is it happening with all the APIs or with selected ones?

**Comment by vkalal** [comment]
due to inactivity closing this issue.

**Comment by yinggu** [comment]
I am facing the same issue when running the test in BurpClientIT.java with burp pro version in headless mode. Do we need manual add burp CA into keystore?
