### ISSUE TITLE
What is 2nd step ? 

### ISSUE THREAD

**Issue by ashwpawar** [vmware/burp-rest-api#19]
In the built and run section , it is mentioned that : 
Create a  lib  folder under the project directory and place the Burp Suite JAR file into it.

we are not able to understand this step . Kindly elaborate on this one . 
Do we need to perform this step ,in burp project , or in the eclipse project while creating a jar file ?

**Comment by vkalal** [comment]
After you check out project, create a lib folder under burp-rest-api project and put burpsuite jar in it. Then you can create new jar.

**Comment by vkalal** [comment]
I am closing this issue, feel free to reopen another issue if you see any issue.
