### ISSUE TITLE
Plans to add more API nodes

### ISSUE THREAD

**Issue by hshar7** [vmware/burp-rest-api#2]
Hello,
Thank you for developing this. Are there any plans in the future to expand this to cover more actions in Burp Suite? Such as Intruder and Repeater attacks?

Thank you,
Hayder

**Comment by hshar7** [comment]
Current api calls if anyone is wondering:
![screen shot 2016-09-23 at 3 25 58 pm](https://cloud.githubusercontent.com/assets/17727543/18800862/19674710-81a5-11e6-978a-1115619efbd7.png)

**Comment by blangus** [comment]
I actually created two actions to stop Burp and to clear the session state. I will create a pull request for it soon.

**Comment by hshar7** [comment]
@blangus awesome, maybe I can look into creating one for intruder and repeater.

**Comment by dmettem** [comment]
Thanks for the feedback and interest in the project.
We welcome the contributions from community. Please feel free to add additional functionality and open pull requests to make it available to everyone.

**Comment by stevespringett** [comment]
@hshar7 thanks for the quick API reference and special thanks to the developers who wrote this. I'm looking forward to using it. If it works as well as I think it will, I'll be including support for automating burp (via this project) in [Hakbot Origin Controller](https://github.com/hakbot/hakbot-origin-controller).

Refer to: https://github.com/hakbot/hakbot-origin-controller/issues/2
