### ISSUE TITLE
Unable to load the API using my project options

### ISSUE THREAD

**Issue by s-rohil** [vmware/burp-rest-api#22]
Team,

I have performed the following steps:
1-used ./gradlew bootRun, I am able to launch an instance of Burp. 
Following instructions in https://github.com/vmware/burp-rest-api/issues/6 and https://github.com/vmware/burp-rest-api/issues/11. 
2-copied my project and user options into "src/main/resources/static/" and then ran the gradlew executable present in the folder structure

- What would be my next steps to run burp scans?

**Comment by gangelino** [comment]
Fixed in https://github.com/vmware/burp-rest-api/pull/28
