### ISSUE TITLE
Allow bind hosts to be configured

### ISSUE THREAD

**Issue by 0xdevalias** [vmware/burp-rest-api#33]
Currently it seems that the burp proxy is binding by default to `localhost`, and that the API is listening on `0.0.0.0`. It would be awesome if we were able to control these by command line arguments in a similar way that we currently can with the port options.

The main line I found in the code that seemed relevant was:
* https://github.com/vmware/burp-rest-api/blob/0fca0b51def3110ce8e0a5c44961eb42739fd345/src/test/java/com/vmware/burp/extension/client/BurpClientIT.java#L60

But not 100% if that is correct, as it seems like it's part of an integration test.

**Comment by ikkisoft** [comment]
You can already change the Proxy settings (e.g. binding IP, port) using Burp's project file (which is supported by _burp-rest-api_)

```
        "request_listeners":[
            {
                "certificate_mode":"per_host",
                "listen_mode":"loopback_only",
                "listener_port":8080,
                "running":true
            }
        ],
```

Btw, the code you've indicated it's just for tests.

**Comment by ikkisoft** [comment]
As commented back then, there are two binding ports (API and Burp Proxy).

- Using the current master and upcoming new release, you can configure the API address/port via command line argument
- Using the 'listeners' configuration in the Burp's project file, you can setup the Burp Proxy address/port

We will be creating a FAQ to clarify the differences.
