### ISSUE TITLE
Get spider status

### ISSUE THREAD

**Issue by 0xdevalias** [vmware/burp-rest-api#35]
There is currently an endpoint that allows the current scan status to be retrieved, but not an equivalent for the spider.

It would be cool to be able to check when it has 'finished spidering', or how many items are left in it's queue (similar to what is shown in the burp UI)

**Comment by 0xdevalias** [comment]
Having a bit of a deeper look into this, it seems that the burp interface may not expose this information:

* https://portswigger.net/burp/extender/api/

**Comment by ikkisoft** [comment]
Despite Burp not exposing this value in the extender APIs, I've implemented an experimental workaround. It's currently available in the PR https://github.com/vmware/burp-rest-api/pull/41 (and it will be hopefully merged to master soon).

**Comment by gangelino** [comment]
Thanks for submitting this PR @ikkisoft!
