### ISSUE TITLE
Burp community jar isn't found

### ISSUE THREAD

**Issue by LucileLeveq** [vmware/burp-rest-api#36]
When using Burp Community jar file for building the project, Gradle fail:
```
PS C:\...\burp-rest-api> .\gradlew clean build
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 !! Make sure that no other Burp instances are running !!
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Updating version to '1.0.2' in src\main\resources\application.yml
:clean
:createschemaTargetDir UP-TO-DATE
:compileJava

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':compileClasspath'.
> Could not find :burpsuite_pro:.
  Required by:
      :burp-rest-api:1.0.2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.973 secs
```

The problem seems to be caused by a dependencies section in "build.gradle" file: 
```
dependencies {
    compile('org.springframework.boot:spring-boot-starter-web')
    compile("org.springframework.boot:spring-boot-starter-jetty")
    compile fileTree(dir: 'lib', include: '**/*.jar')
    compile "io.springfox:springfox-swagger2:2.+"
    compile "io.springfox:springfox-swagger-ui:2.+"
    
    compile name: 'burpsuite_pro'

    testCompile('org.springframework.boot:spring-boot-starter-test')
    testCompile('org.apache.httpcomponents:httpclient:4.5.2')

    jaxb 'org.glassfish.jaxb:jaxb-jxc:2.+'
	jaxb 'org.glassfish.jaxb:jaxb-xjc:2.+'
}
```
Because the community version jar file is named "burpsuite_community_v.X.X.X.jar" it is not recognized as a correct jar file. I solved my problem by rename my file "burpsuite_pro.jar" as expected by Gradle and then it works, but that's not really userfriendly. Maybe you should correct that in the dependencies or precise this solution in your README file ? 

Regards.

EDIT : Some precisions about the environment : Windows 7, Burp Community (with jar file version 1.7.32), Gradle 4.6, Java 1.8

**Comment by LucileLeveq** [comment]
I'd like to use it to automate some scans. I have read in your "README.md" that I could use the community edition with limited capabilities and some of the command lines like `java -jar build/libs/burp-rest-api-1.0.2.jar --burp.edition=free # for free edition` are precisely for this use. So I supposed that it was supported, am I wrong ? If it's not, maybe you should clarify it ?

**Comment by ikkisoft** [comment]
_Disclaimer_: despite actively contributing to the project, I am not the actual maintainer

Burp Community does not allow the use of the scanner (https://portswigger.net/burp), thus you won't be able to automate scans. For this reason, I don't think it makes sense to maintain support for this version and this is also why I was trying to understand the specific use case.

**Comment by LucileLeveq** [comment]
So you should clarify it for the next developpers ;)

**Comment by henshin** [comment]
I was having the same problem although I was using Burp Pro. Gradle doesn't seem to pickup the burp jar file from the lib folder unless the name is "burpsuite_pro.jar".
The documentation should be more clear regarding this.

**Comment by gangelino** [comment]
@LucileLeveq @henshin could you please submit a PR to update the README? thanks!

**Comment by ikkisoft** [comment]
There is also legacy code related to the community version that would need to be removed.

**Comment by henshin** [comment]
@gangelino it seems that i have to sign the CLA in order to make pull requests and provide a lot info about myself... this is not really pratical. Anyway this one is a really trivial change, on the "Build & Run", just specify that the filename should be called burpsuite_pro.jar.

**Comment by ikkisoft** [comment]
As of version 1.0.4, Burp Free/Community is no longer supported. Please see the discussion in https://github.com/vmware/burp-rest-api/pull/71
