### ISSUE TITLE
Getting Failed to apply plugin [class 'io.spring.gradle.dependencymanagement.DependencyManagementPlugin']

### ISSUE THREAD

**Issue by nishmastercoder** [vmware/burp-rest-api#37]
While trying to build the project via gradle build I am getting following error message:-
A problem occurred evaluating root project 'burp-rest-api-master'.
> Failed to apply plugin [class 'io.spring.gradle.dependencymanagement.DependencyManagementPlugin']
   > Could not create task of type 'DependencyManagementReportTask'.

Gradle version :- 4.6
Groovy version :- 2.4.12

Can someone help me out ? I need to use these RestAPI soon

Thanks,
NIshant Shah

**Comment by nishmastercoder** [comment]
Nee to solve this issue soon.
Any help would be highly appreciated.
Thanks,
Nishant Shah

**Comment by TuxOtaku** [comment]
I'm seeing the same error. Exact same runtime environment as @nishmastercoder.

**Comment by nishmastercoder** [comment]
I downgraded to gradle version 2.13 and then it started working fine for me.

**Comment by adeleglise** [comment]
I was seeing the same issue.

I downgraded to gradle 2.13, and I can confirm that it solves the problem. Thanks @nishmastercoder

**Comment by ikkisoft** [comment]
Btw, see https://github.com/vmware/burp-rest-api/blob/master/FAQ.md
