### ISSUE TITLE
Issue with the implementation of IBurpExtender class

### ISSUE THREAD

**Issue by dkogue** [vmware/burp-rest-api#42]
Having these errors after running  gradlew bootRun

java:11: error: cannot find symbol
public class BurpExtender implements IBurpExtender {
                                     ^
  symbol: class IBurpExtender
/home/burp-rest-api/src/main/java/burp/BurpExtender.java:14: error: cannot find symbol
    private IBurpExtenderCallbacks callbacks;
            ^
  symbol:   class IBurpExtenderCallbacks
  location: class BurpExtender
/home/burp-rest-api/src/main/java/burp/BurpExtender.java:15: error: cannot find symbol
    private IExtensionHelpers helpers;
            ^
  symbol:   class IExtensionHelpers
  location: class BurpExtender
/home/burp-rest-api/src/main/java/burp/BurpExtender.java:31: error: cannot find symbol
    public void registerExtenderCallbacks(IBurpExtenderCallbacks callbacks) {
                                          ^
  symbol:   class IBurpExtenderCallbacks
  location: class BurpExtender
/home/burp-rest-api/src/main/java/burp/BurpExtender.java:46: error: cannot find symbol
    public IBurpExtenderCallbacks getCallbacks() {
           ^
  symbol:   class IBurpExtenderCallbacks
  location: class BurpExtender
/home/burp-rest-api/src/main/java/burp/BurpExtender.java:50: error: cannot find symbol
    public IExtensionHelpers getHelpers() {
           ^
  symbol:   class IExtensionHelpers
  location: class BurpExtender
/home/burp-rest-api/src/main/java/com/vmware/burp/extension/domain/HttpMessage.java:10: error: cannot find symbol
import burp.IExtensionHelpers;
           ^
  symbol:   class IExtensionHelpers
  location: package burp
/home/burp-rest-api/src/main/java/com/vmware/burp/extension/domain/HttpMessage.java:11: error: cannot find symbol
import burp.IHttpRequestResponse;
           ^
  symbol:   class IHttpRequestResponse
  location: package burp
/home/burp-rest-api/src/main/java/com/vmware/burp/extension/domain/HttpMessage.java:59: error: cannot find symbol
   public HttpMessage(IHttpRequestResponse iHttpRequestResponse) {
                      ^
  symbol:   class IHttpRequestResponse
  location: class HttpMessage
/home/burp-rest-api/src/main/java/com/vmware/burp/extension/domain/ScanIssue.java:9: error: cannot find symbol
import burp.IHttpRequestResponse;
           ^
  symbol:   class IHttpRequestResponse
  location: package burp
/home/burp-rest-api/src/main/java/com/vmware/burp/extension/domain/ScanIssue.java:10: error: cannot find symbol
import burp.IScanIssue;
           ^
  symbol:   class IScanIssue
  location: package burp
/home/burp-rest-api/src/main/java/com/vmware/burp/extension/domain/ScanIssue.java:65: error: cannot find symbol
   public ScanIssue(IScanIssue iScanIssue) {
                    ^
  symbol:   class IScanIssue
  location: class ScanIssue
/home/burp-rest-api/src/main/java/com/vmware/burp/extension/domain/internal/SpiderQueueMap.java:10: error: cannot find symbol
import burp.IHttpRequestResponse;
           ^
  symbol:   class IHttpRequestResponse
  location: package burp
/home/burp-rest-api/src/main/java/com/vmware/burp/extension/domain/internal/SpiderQueueMap.java:24: error: cannot find symbol
    private Map<String, IHttpRequestResponse[]> map = new HashMap<>();
                        ^
  symbol:   class IHttpRequestResponse
  location: class SpiderQueueMap
/home/burp-rest-api/src/main/java/com/vmware/burp/extension/domain/internal/SpiderQueueMap.java:30: error: cannot find symbol
    public void addItem(String url, IHttpRequestResponse[] siteMapUrl) {
                                    ^
  symbol:   class IHttpRequestResponse
  location: class SpiderQueueMap
/home/burp-rest-api/src/main/java/com/vmware/burp/extension/domain/internal/SpiderQueueMap.java:52: error: cannot find symbol
    private IHttpRequestResponse[] getQueue(String url) {
            ^
  symbol:   class IHttpRequestResponse
  location: class SpiderQueueMap
/home/burp-rest-api/src/main/java/com/vmware/burp/extension/domain/internal/SpiderQueueMap.java:61: error: cannot find symbol
    private boolean compareSiteMap(IHttpRequestResponse[] newSiteMap, IHttpRequestResponse[] oldSiteMap){
                                   ^
  symbol:   class IHttpRequestResponse
  location: class SpiderQueueMap
/home/burp-rest-api/src/main/java/com/vmware/burp/extension/domain/internal/SpiderQueueMap.java:61: error: cannot find symbol
    private boolean compareSiteMap(IHttpRequestResponse[] newSiteMap, IHttpRequestResponse[] oldSiteMap){
                                                                      ^
  symbol:   class IHttpRequestResponse
  location: class SpiderQueueMap
/home/burp-rest-api/src/main/java/com/vmware/burp/extension/domain/internal/ScanQueueMap.java:9: error: cannot find symbol
import burp.IScanQueueItem;
           ^
  symbol:   class IScanQueueItem
  location: package burp
/home/burp-rest-api/src/main/java/com/vmware/burp/extension/domain/internal/ScanQueueMap.java:22: error: cannot find symbol
   private Map<String, List<IScanQueueItem>> map = new HashMap<>();
                            ^
  symbol:   class IScanQueueItem
  location: class ScanQueueMap
/home/burp-rest-api/src/main/java/com/vmware/burp/extension/domain/internal/ScanQueueMap.java:24: error: cannot find symbol
   public void addItem(String url, IScanQueueItem iScanQueueItem) {
                                   ^
  symbol:   class IScanQueueItem
  location: class ScanQueueMap
/home/burp-rest-api/src/main/java/com/vmware/burp/extension/domain/internal/ScanQueueMap.java:51: error: cannot find symbol
   private List<IScanQueueItem> getQueue(String url) {
                ^
  symbol:   class IScanQueueItem
  location: class ScanQueueMap
/home/burp-rest-api/src/main/java/com/vmware/burp/extension/service/BurpService.java:10: error: cannot find symbol
import burp.IHttpRequestResponse;
           ^
  symbol:   class IHttpRequestResponse
  location: package burp
/home/burp-rest-api/src/main/java/com/vmware/burp/extension/service/BurpService.java:11: error: cannot find symbol
import burp.IScanIssue;
           ^
  symbol:   class IScanIssue
  location: package burp
/home/burp-rest-api/src/main/java/com/vmware/burp/extension/service/BurpService.java:12: error: cannot find symbol
import burp.IScanQueueItem;
           ^
  symbol:   class IScanQueueItem
  location: package burp
/home/burp-rest-api/src/main/java/burp/BurpExtender.java:30: error: method does not override or implement a method from a supertype
    @Override
    ^
/home/burp-rest-api/src/main/java/com/vmware/burp/extension/domain/HttpMessage.java:63: error: cannot find symbol
      IExtensionHelpers helpers = BurpExtender.getInstance().getHelpers();
      ^
  symbol:   class IExtensionHelpers
  location: class HttpMessage
/home/burp-rest-api/src/main/java/com/vmware/burp/extension/domain/ScanIssue.java:81: error: cannot find symbol
         IHttpRequestResponse iHttpRequestResponse = iScanIssue.getHttpMessages()[i];
         ^
  symbol:   class IHttpRequestResponse
  location: class ScanIssue
/home/burp-rest-api/src/main/java/com/vmware/burp/extension/domain/internal/SpiderQueueMap.java:88: error: cannot find symbol
            IHttpRequestResponse[] httpMessageListOld = map.get(url);
            ^
  symbol:   class IHttpRequestResponse
  location: class SpiderQueueMap
/home/burp-rest-api/src/main/java/com/vmware/burp/extension/domain/internal/SpiderQueueMap.java:89: error: cannot find symbol
            IHttpRequestResponse[] httpMessageListNew = BurpExtender.getInstance().getCallbacks().getSiteMap(url);
            ^
  symbol:   class IHttpRequestResponse
  location: class SpiderQueueMap
/home/burp-rest-api/src/main/java/com/vmware/burp/extension/domain/internal/ScanQueueMap.java:26: error: cannot find symbol
         List<IScanQueueItem> list = map.get(url);
              ^
  symbol:   class IScanQueueItem
  location: class ScanQueueMap
/home/burp-rest-api/src/main/java/com/vmware/burp/extension/domain/internal/ScanQueueMap.java:30: error: cannot find symbol
         List<IScanQueueItem> list = new ArrayList<>();
              ^
  symbol:   class IScanQueueItem
  location: class ScanQueueMap
/home/burp-rest-api/src/main/java/com/vmware/burp/extension/domain/internal/ScanQueueMap.java:68: error: cannot find symbol
         for (IScanQueueItem iScanQueueItem : getQueue(url)) {
              ^
  symbol:   class IScanQueueItem
  location: class ScanQueueMap
/home/burp-rest-api/src/main/java/com/vmware/burp/extension/service/BurpService.java:108: error: cannot find symbol
        burp.StartBurp.main(burpOptions);
            ^
  symbol:   class StartBurp
  location: package burp
/home/burp-rest-api/src/main/java/com/vmware/burp/extension/service/BurpService.java:170: error: cannot find symbol
        for (IHttpRequestResponse iHttpRequestResponse : BurpExtender.getInstance().getCallbacks()
             ^
  symbol:   class IHttpRequestResponse
  location: class BurpService
/home/burp-rest-api/src/main/java/com/vmware/burp/extension/service/BurpService.java:183: error: cannot find symbol
            IHttpRequestResponse[] siteMapInScope = BurpExtender.getInstance().getCallbacks().getSiteMap(baseUrl);
            ^
  symbol:   class IHttpRequestResponse
  location: class BurpService
/home/burp-rest-api/src/main/java/com/vmware/burp/extension/service/BurpService.java:185: error: cannot find symbol
            for (IHttpRequestResponse iHttpRequestResponse : siteMapInScope) {
                 ^
  symbol:   class IHttpRequestResponse
  location: class BurpService
/home/burp-rest-api/src/main/java/com/vmware/burp/extension/service/BurpService.java:195: error: cannot find symbol
					IScanQueueItem iScanQueueItem = BurpExtender.getInstance().getCallbacks()
					^
  symbol:   class IScanQueueItem
  location: class BurpService
/home/burp-rest-api/src/main/java/com/vmware/burp/extension/service/BurpService.java:222: error: cannot find symbol
        for (IHttpRequestResponse iHttpRequestResponse : BurpExtender.getInstance().getCallbacks()
             ^
  symbol:   class IHttpRequestResponse
  location: class BurpService
/home/burp-rest-api/src/main/java/com/vmware/burp/extension/service/BurpService.java:250: error: cannot find symbol
        IScanIssue[] iScanIssues = BurpExtender.getInstance().getCallbacks()
        ^
  symbol:   class IScanIssue
  location: class BurpService
/home/burp-rest-api/src/main/java/com/vmware/burp/extension/service/BurpService.java:252: error: cannot find symbol
        for (IScanIssue iScanIssue : iScanIssues) {
             ^
  symbol:   class IScanIssue
  location: class BurpService
41 errors
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by ikkisoft** [comment]
It looks like gradlew doesn't properly resolve the Burp.jar. Have you placed the JAR in the /lib folder, as described in the README?

Btw, we're currently working on a big change to make this step unnecessary.
