### ISSUE TITLE
Improve site map model

### ISSUE THREAD

**Issue by arnKo** [vmware/burp-rest-api#43]
The api's model for `getSitemap` has currently the following properties:
```javascript
{
    comment,
    highlight,
    host,
    port,
    protocol,
    request, // Specified in documentation, but not included in response
    response, // Specified in documentation, but not included in response
    statusCode,
    url,
}
```

This set of properties is incomplete in terms of being able to identify a particular request, because the `method` property is missing. Especially, since `request` and `response`, from which the method could be extracted, are excluded from the api's response. 

The method of a request can simply be obtained by:
```java
IExtensionHelpers helpers = BurpExtender.getInstance().getHelpers();
String method = helpers.analyzeRequest(iHttpRequestResponse).getMethod();
```
As it is done for other value such as `url` in the class `HttpMessage`.

Also, other useful information, that burp provides to its extensions, should be added to the model:
```java
if ((iHttpRequestResponse.getResponse() != null)) {
    List<ICookie> cookies = helpers.analyzeResponse(iHttpRequestResponse).getCookies();
    List<String> headers = helpers.analyzeResponse(iHttpRequestResponse).getHeaders();
}
```

**Comment by gangelino** [comment]
Good findings, could you please submit a PR? :)
