### ISSUE TITLE
Predefined scope appears to be resetting

### ISSUE THREAD

**Issue by jonatanhal** [vmware/burp-rest-api#49]
Pre-existing scopes for projects appear to be reset upon opening a project.

Steps to reproduce:
1. Using burpsuite, open a new project & add https://example.com to the scope. Exit burpsuite.
2. Using burp-rest-api, open the previously created project. At this point it appears that the https://example.com scope is no longer there. 

Burpsuite version: 1.7.34

**Comment by lestatk0** [comment]
If you are using burpa with it, then you should make a curl before you start your tests. It helps

**Comment by ikkisoft** [comment]
I believe you're using the wrong argument for loading the configuration file.

On the latest release, the following command works and properly restores the scope:
```$ java -jar burp-rest-api-2.0.0.jar --headless.mode=false --burp.jar=./lib/burpsuite_pro_v2.0.10.jar --config-file=<PATH TO Project Config File .json>```
