### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by blangus** [vmware/burp-rest-api#5]
Hi guys, lately I have been having the following error when trying to build the burp-rest-api. The following test fails when building.

com.vmware.burp.extension.client.BurpClientIT > testConfigMethods FAILED
    java.lang.IllegalStateException
        Caused by: org.springframework.context.ApplicationContextException
            Caused by: java.lang.NoSuchMethodError

When I run the burp-rest-api.jar the following error shows up:

org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NoSuchMethodError: springfox.documentation.spi.service.contexts.RequestMappingContext.getHandlerMethod()Lorg/springframework/web/method/HandlerMethod;

I have tried it with a clean code base and burp suite pro file but this issue remains. It looks like it has something to do with Spring but I couldn't figure it out. Did someone else also encounter this problem?

**Comment by dmettem** [comment]
@blangus Please pull the latest code and try again. Let me know how it works. Thanks!

**Comment by blangus** [comment]
This has fixed the issue! Thanks a lot!
