### ISSUE TITLE
Not able to start with free edition.

### ISSUE THREAD

**Issue by Akashkansal065** [vmware/burp-rest-api#50]
Hi ,

after running the commands

    gradlew clean build
    # and run it
    java -jar build/libs/burp-rest-api-1.0.2.jar --burp.edition=free # for free edition

Throwing exception.
![image](https://user-images.githubusercontent.com/29590447/42145244-e5cfa15e-7ddd-11e8-98d0-60fecbe0c8ad.png)

![image](https://user-images.githubusercontent.com/29590447/42145208-9bd9050e-7ddd-11e8-84f4-5a3972fe4418.png)

It will be better if you could please share a video with free edition.
Not able to understand this null pointer exception.

**Comment by lazorgator** [comment]
@Akashkansal065 Try to let the maintainers know whether the patch works for you or not so they can close issues that are resolved
