### ISSUE TITLE
Missing code

### ISSUE THREAD

**Issue by LuongVinhKhang** [vmware/burp-rest-api#54]
Hi team,

Please fix by add missing ')' to this file :
burp-rest-api\src\main\java\com\vmware\burp\extension\service\BurpService.java
line 74: error: ')' expected

Thanks

**Comment by gangelino** [comment]
Good catch! Would you mind submitting a PR with the fix? Thanks :)

**Comment by LuongVinhKhang** [comment]
Okay. :)

**Comment by LuongVinhKhang** [comment]
Issue fixed by PR #55, closing it now.
