### ISSUE TITLE
Scanner scans not existing pages

### ISSUE THREAD

**Issue by arnKo** [vmware/burp-rest-api#56]
While trying to figure out why my scans take longer than anticipated, I discovered scan queue items of pages that do not exist in my web application. 

I show the problem with an example:

My web application consists of `http://localhost/` and `http://localhost/task/show`.
I add the `http://localhost` to the scope, set it as spider seed and use it to initiate an active scan.
My site map contains of:
```
http://localhost
  task
    show
```
And my scan queue contains of:
* http://localhost
* http://localhost/task
* http://localhost/task/show

I do not expect and I do not want to scan the second URL, as it does not exist in my application.
It seems like calling `IBurpExtenderCallbacks.getSiteMap()`returns an entry for this path, too, although burp - more precisely burp's spider - never issued a request to `http://localhost/task`. 

We can also observe this behavior when calling the rest API to obtain the site map. It outputs entries without a response, which is checked in the `HttpMessage` class:
```java
if (iHttpRequestResponse.getResponse() != null) {
...
}
```

The solution here would be to only send a site map entry to the scanner, if it has a response:
```java
public class BurpService {
...
  public boolean scan(String baseUrl, boolean isActive)
            throws MalformedURLException {
...
        for (IHttpRequestResponse iHttpRequestResponse : siteMapInScope) {
          if (iHttpRequestResponse.getResponse() == null) {
            continue;
          }
...
```

**Comment by ikkisoft** [comment]
Merged your PR, thus we can close this issue. Thanks again for the contribution!
