### ISSUE TITLE
Has anyone successfully gotten this to run lately?

### ISSUE THREAD

**Issue by dsolstad** [vmware/burp-rest-api#59]
I tried to use the 2.13 version of Gradle as suggested, but nothing happens. Tried Burp Pro on latest Kali and Ubuntu.

**Comment by kbroughton** [comment]
I just did.

I got it working with headless=false

https://github.com/vmware/burp-rest-api/issues/60

**Comment by ikkisoft** [comment]
Please provide more details if you have any specific problem.
