### ISSUE TITLE
Burp Extensions not loading

### ISSUE THREAD

**Issue by l50** [vmware/burp-rest-api#6]
When using the Rest API, the only extension which successfully loads is the Burp Rest Extension. Upon trying to load a Java extension, you are presented with an error message stating:

java.lang.Exception: Extension does not implement any usable methods

Python extensions give a message along these lines:
java.lang.ClassCastException: org.python.core.PySingleton cannot be cast to burp.IBurpExtender

When using Burp normally with the traditional
`java -jar <location to burp jar>`
the extensions work without issue. 

The Extension options are consistent across both the Rest API instance of Burp and the normal instance you would run with Burp.

- Running Burp 1.7.13 on OSX El Capitan (10.11.6)
- Running Java version 8

-- Confirmed to be a problem on Burp 1.7.14 as well.

**Comment by SymbianSyMoh** [comment]
Any updates on this issue?

I tried to load extensions from BApp Store or even manually but with no success, So i think the solution may to have the "Burp Rest Extension" as an external one and load it individually.

PS: i tested both normal burp start and headless mode and both of them are loading extensions with no problem, the problem is with the "Burp Rest Extension"

My burp suite version is: Pro v1.7.22

**Comment by SymbianSyMoh** [comment]
*UPDATE*
Fixed by running burp with gradle not running the builded version.

**Comment by l50** [comment]
Confirmed, running burp with gradle resolved the issue. Thank you.

**Comment by SymbianSyMoh** [comment]
@l50 You welcome, yes i managed to get project-config, user-config and project file work in gradle.

All what you need to do is:
1. Regarding project-config and user-config you can edit the default files bundled with gradle which you can find it here: src/main/resources/static/

2. Regarding the project-file you can edit this line:
`   private static final String TEMPORARY_PROJECT_FILE_NAME = "/path/to/project/file.burp";  `
in the file:
/src/main/java/com/vmware/burp/extension/service/BurpService.java

before executing gradle

**Comment by l50** [comment]
Thank you sir. I'll go ahead and close this issue permanently now - just wanted to be sure the functionality you get with running the jar can be done with gradlew.
