### ISSUE TITLE
enhancement: add docs for headless=false

### ISSUE THREAD

**Issue by kbroughton** [vmware/burp-rest-api#60]
Hi!

It took a little while, but I have X11 forwarding working from my osx laptop to an ec2 instance.

If desired, i can create a PR to the docs.  Steps:

I followed http://www.brianlinkletter.com/how-to-run-gui-applications-xfce-on-an-amazon-aws-cloud-server-instance/

My ssh X11 forwarding looked like this
mac> ssh -X -L 5901:localhost:5901 -i ~/path_to_privatekey ubuntu@ip -vv

After installing vncserver as per biranlinkletter, the main differences were
1. to match his settings, commented out #X11DisplayOffset 10
2. instead of linux vnc client i used
    mac> open vnc://localhost:5901

This opened an Xterm on my mac, but I got display errors.

I solved this by setting
AWS> export DISPLAY=localhost:1

Probably the most robust way to find out the Display port running vncserver is to check the
:600N entry below.  N is the port, in my case, 1.

ubuntu@ip-172-31-17-158:~$ netstat -plan | grep LISTEN
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 0.0.0.0:6001            0.0.0.0:*               LISTEN      2124/Xvnc4
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -
tcp6       0      0 :::5901                 :::*                    LISTEN      2124/Xvnc4
tcp6       0      0 127.0.0.1:8080          :::*                    LISTEN      3525/java
tcp6       0      0 :::22                   :::*                    LISTEN      -

**Comment by ikkisoft** [comment]
Included this issue/question in https://github.com/vmware/burp-rest-api/blob/master/FAQ.md
