### ISSUE TITLE
Error on run : "Burp project files are not supported on this edition of Burp"

### ISSUE THREAD

**Issue by lampalork85** [vmware/burp-rest-api#66]
Hello,

After a successfull build I tried to run with this command : 
java -jar build/libs/burp-rest-api-1.0.3.jar --burp.edition=free
and i got this error : 

"Burp project files are not supported on this edition of Burp"

Any idea ?

Thx

**Comment by ikkisoft** [comment]
This should be now fixed. Please re-open an issue if that's not the case.
