### ISSUE TITLE
New License key

### ISSUE THREAD

**Issue by poulomibasu** [vmware/burp-rest-api#69]
Hi Team,

I had activated Burp while running jar file using trial license. I want to run the burp rest api using new license.  Can you please help in this regard?

**Comment by karthikbs23** [comment]
Hi,

Open Burp Jar and navigate to
Help->License-> Update License key

Cheers!

**Comment by ikkisoft** [comment]
When you run _burp-rest-api_ from the machine where you activated Burp , everything should just work. Please re-open an issue with more details, if you think there's a bug. Thanks!
