### ISSUE TITLE
Adding jar releases 

### ISSUE THREAD

**Issue by PaulSec** [vmware/burp-rest-api#7]
Hi there, 

First of all, great work and pretty cool extension! 
Is there any chance you could provide .jar in the release section? That would be really helpful. 

Thanks,

**Comment by khuongduybui** [comment]
Releasing the built jar means distributing a **licensed** Burp Suite jar. That's hairy.

**Comment by PaulSec** [comment]
Yeah, that's really problematic. 
I saw bunch of *.jar released as Burp Extensions and I was wondering why there was none for this one..
