### ISSUE TITLE
[Request] Can you make a way to load other extensions with burp-rest-api more easier

### ISSUE THREAD

**Issue by j3ssie** [vmware/burp-rest-api#76]
**This is just a request**
I know you guy have the option `--burp.ext=<filename.{jar,rb,py}` to load other extensions.
But I've installed many extension for Burp(many of them required Jython), loading burp-rest-api with bunch of options for that extension is really painful. 
Maybe I'm did something wrong(correct me if I'm wrong) cause after I start burp-rest-api and install some extension then restart burp-rest-api those extension I installed completely disappear.

So can you make option for loading many extension easier like `--burp.ext.folder=` for example or do it like Burp original is loading it without specific anything.

**Desktop:**
 - OS: Mac OS 10.14
 - Burp Suite _Professional_ version v2.0.09beta
 - Extension **burp-rest-api** version 2.0.1

**Comment by thypon** [comment]
Hi @j3ssie , the `--burp.ext=` option is only a way to include new extensions from the command line easily.
It is still possible to include them with a custom `--user-config-file=` like in *normal* burp.

**Comment by j3ssie** [comment]
Yeah I got it.
But another issue is after I used Burp with burp-rest-api and exit it then run original Burp I got no extension.

**Comment by thypon** [comment]
What you are experiencing it is the expected burp-rest-api behaviour. When it starts up it generates a new temporary user-config-file derived from the auto saved, user-config-file. Before exiting, burp-rest-api removes the temporary user-config-file

**Comment by thypon** [comment]
What you are experiencing it is the expected `burp-rest-api` behaviour. When it starts up it generates a new temporary `user-config-file`. Before exiting, `burp-rest-api` removes the temporary `user-config-file`.What you are experiencing is Burp Suite trying to access an unexistent `user-config-file`.

**Comment by ikkisoft** [comment]
Closing this issue as for @thypon response. Please reopen an issue with step by step instructions, if you think there is a bug.
