### ISSUE TITLE
Python extensions cannot be configured with relative paths

### ISSUE THREAD

**Issue by Crimdrac** [vmware/burp-rest-api#79]
**Describe the bug**
I am starting burp-rest-api with Java and Python extensions using the 
--burp.ext option.
For Java extensions I can use a relative file path, e.g., --burp.ext=./extensions/burp-retire-js-3.jar
For Pyhton extensions the use of relative file paths does not work. E.g., when using --burp.ext=./extensions/Burp-MissingScannerChecks.py the extension does not get loaded.

**To Reproduce**
1. Copy Burp-MissingScannerChecks.py (source: https://github.com/PortSwigger/additional-scanner-checks/blob/master/Burp-MissingScannerChecks.py) to a directory 'extensions'
2. Configure jython-standalone-2.7.0.jar in the user options config file.
3. Start burp-rest-api with --burp.ext=./extensions/Burp-MissingScannerChecks.py
2. Burp starts up. 
3. Select the 'Extender' tab. The Burp-MissingScannerChecks.py is listed but the 'loaded' checkbox is not set.
4. Select the 'Alert' tab: It shows 'Fail to load extension: ./extension/ Burp-MissingScannerChecks.py'

**Expected behavior**
The 'Extender' tab shows that the Burp-MissingScannerChecks.py extensions is loaded. No alert is listed.

**Desktop (please complete the following information):**
 - OS: Mac
 - Burp Suite Professional version 1.7.37
 - Extension burp-rest-api 2.0.1

**Comment by ikkisoft** [comment]
Thanks for the notification. We will take a look. cc: @thypon

**Comment by ikkisoft** [comment]
Fixed and already in master! A new release coming soon...

**Comment by peterzh4ng** [comment]
Well, ah I found a same problem in Burpsuite, that if I configure a plugin using relative path in the configuration json file, jar extensions would be loaded quite well, but not the python things.
Python plugin would not be loaded due to a FileNotFound error:
```
IOError: (2, 'File not found - E:\\xxx\\.tools\\.main\\burpsuite\\.plugins\\bapps_SourceMapper\\.plugins\\bapps_SourceMapper\\SourceMapper.py (The system cannot find the path specified)')
```
