### ISSUE TITLE
Progress reporting broken

### ISSUE THREAD

**Issue by torgils** [vmware/burp-rest-api#80]
Progress reporting from both the spider and scanner endpoints seem broken.

**To Reproduce**
- Start a scan or spidering and then request the status.

**Expected behavior**
Expecting the percentage to update but it just stays at 0 until complete

**Comment by ikkisoft** [comment]
Which version on burp-rest-api and Burp Pro?

Just tested on  _burp-rest-api-2.0.1_ and _burpsuite_pro_v2.0.11_, spider status works but scanner status seems to have problems (or it takes a very long time for simple scan). Maybe a bug in the latest Burp Pro beta?

**Comment by torgils** [comment]
Tried it today with 1.7.37 and the % reporting works fine and the active scan seems much quicker so definitely something in the beta that's changed/broken.

**Comment by ikkisoft** [comment]
Thanks for getting back. I will notify PortSwigger via support.

**Comment by ikkisoft** [comment]
https://support.portswigger.net/customer/en/portal/questions/17438422-v2-x-extender-api-iscanqueueitem-getpercentagecomplete-does-not-work-?new=17438422

**Comment by ikkisoft** [comment]
From the response in the forum, it seems that https://portswigger.net/burp/extender/api/burp/IScanQueueItem.html is deprecated in Burp v2 :(
