### ISSUE TITLE
Task Execution Paused

### ISSUE THREAD

**Issue by Regala** [vmware/burp-rest-api#84]
**Describe the bug**
Every time I start Burp, headless or not the "Task Execution" option is paused. This means that no matter how many tasks I send (spider, passive, active scan) they will only be added and not actually executed, since all the tasks are paused. I can observe that by running with headless=false:

<img width="563" alt="tasks" src="https://user-images.githubusercontent.com/1380527/49934040-379f4f80-fec5-11e8-9606-3e2f03e678a9.png">

I've tried changing that option and then saving project options, user options and project state - it still stays 'paused'.

**To Reproduce**
I'm just Adding Target -> Check if it's in scope -> Start spider (/burp/spider?baseUrl).

**Desktop (please complete the following information):**
 - OS: Mac
 - Burp Suite _Professional_2.0.09 version
 - Extension **burp-rest-api-2.0.0** version 

Not if there is something I'm missing.

**Comment by ikkisoft** [comment]
That's the default behaviour in Burp.

You can use the following command line ```--unpause-spider-and-scanner``` or simply run in headless mode (which won't pause spider and scanner) 

Cheers,
Luca

**Comment by m4udSec** [comment]
i`m using --unpause-spider-and-scanner and ran into same problem, any progress on the matter ?

**Comment by ikkisoft** [comment]
Unless you provide step by step instructions, we won't be able to help you. I don't believe there's any bug since it is all native Burp stuff
