### ISSUE TITLE
Report is not having instances of Issue

### ISSUE THREAD

**Issue by karibasavaraj-sec** [vmware/burp-rest-api#86]
Report is not having instances of Issues

Perform Active Scan with help of burp-rest-api-2.0.0.jar
Use the "GET /burp/report" to get the report

I am not able to get instances of issues in the report.

When I go to Scanner, I see that there are 4 instances for the Issue.
When I generate the report with "GET /burp/report"  API, I get only the Issue and I do not get the instances.

Attached is screenshot from the scanner.

Please can you comment

Thanks in advance,
Karibasavaraj K
<img width="1507" alt="scanner" src="https://user-images.githubusercontent.com/46919944/51690044-e5059700-201d-11e9-9166-3c3e6eb5e1c5.png">

**Comment by ikkisoft** [comment]
What do you mean with "I get only the Issue and I do not get the instances"?
Can you clarify step-by-step what you're doing?

To make sure that it's a not bug in Burp itself, execute the same operation from the Burp GUI and compare the results with the Burp-Rest-API results.

Thanks,
Luca

**Comment by ikkisoft** [comment]
I assume this isn't an issue since few months passed. Can you please confirm?
