### ISSUE TITLE
how to tell burp run in this --unpause-spider-and-scanner mode

### ISSUE THREAD

**Issue by vulntor** [vmware/burp-rest-api#87]
Which place should i add --unpause-spider-and-scanner in the command line? Before --burp.jar or after seems not working. So how can i  tell burp to run in this mode?

**Comment by ikkisoft** [comment]
When you run ```burp-rest-api``` in headless mode ```--headless.mode=false```, Burp is started headless and both spider and scanner are already unpaused.

**Comment by vulntor** [comment]
thanks but i need it to run with ui..

**Comment by ikkisoft** [comment]
I believe this is not currently supported. 

AFAIR, we could just pass the command line arguments here https://github.com/vmware/burp-rest-api/blob/master/src/main/java/com/vmware/burp/extension/service/BurpService.java#L123 but this would need to be tested.

**Comment by vulntor** [comment]
thank you~

**Comment by ikkisoft** [comment]
This was implemented and it's already in master. We're planning to make a new release soon!
