### ISSUE TITLE
Active scan with manual insertion point via REST API

### ISSUE THREAD

**Issue by dpnishant** [vmware/burp-rest-api#88]
Hi,

This project seems to be very promising for a security scanning automation requirement we have in our organization. I was wondering if there is there an interface where we can run an **active scan with manual insertion points** (Burp Intruder's Sniper Attack) and control the active scan configurations (such as Vulnerability, Payload processing etc.) If this interface doesn't exist yet, is this in the roadmap? What's the ETA? 

Finally, if we want to get started with developing this feature what is the best way to get up to speed i.e. get familiar with the project structure, packages/libraries etc.? Any documentation, IRC, Slack channel where we can ask trivial questions.

Thanks

**Comment by ikkisoft** [comment]
Burp Pro does provide an extender method that would allow manual insertion points in the active scan, however this API is not yet exposed via REST by this project. 

```doActiveScan(java.lang.String host, int port, boolean useHttps, byte[] request, java.util.List<int[]> insertionPointOffsets)```

It would be useful to have and seems aligned with the project's goal, so I would definitely consider it as a valid feature request. Please note that this project is mainly supported by me and my colleagues at [Doyensec](https://doyensec.com/) during our 25% research time, so we don't have precise releases/roadmap and cannot provide a precise ETA. Our company does provide commercial support, if necessary. 

Besides the README and the auto-generated Swagger, we don't have additional documentation. All [Burp Pro exposed-APIs](https://portswigger.net/burp/extender/api/burp/IBurpExtenderCallbacks.html) are defined in https://github.com/vmware/burp-rest-api/blob/master/src/main/java/com/vmware/burp/extension/service/BurpService.java

Feel free to ask questions via Issues/email. If we can help, we would be happy to do so.

**Comment by ikkisoft** [comment]
We've sponsored a two days bug squash, and finally pushed this new feature too!  It's already in master, and we will push a new release soon...

![image](https://user-images.githubusercontent.com/6027823/79209785-2614e180-7e44-11ea-84a0-04b282d7a0d6.png)
