### ISSUE TITLE
Maximum time exceeded in code analysis

### ISSUE THREAD

**Issue by eugui** [vmware/burp-rest-api#89]
Hi there,

I'm having problem when I have a list of files (37) and then I get the message:

Task 4: Maximum time exceeded in code analysis of: /burpsuite/11/

I'm using this burp rest api: burp-rest-api-2.0.1.jar

I would like to know how i can increase this time.

**Comment by ikkisoft** [comment]
You can modify this value (**max_time_per_item**) in the projects JSON file

```
"scanner":{
        "static_code_analysis":{
            "max_time_per_item":120,
            "mode":"active_only"
}
```
