### ISSUE TITLE
Support free edition of Burp

### ISSUE THREAD

**Issue by khuongduybui** [vmware/burp-rest-api#9]
Because why not?

I tested the build process with a free-edition jar.
I got an error when trying to run the built jar because ```--project-file``` argument is only supported in Pro version. I slightly modify BurpService.java to suppress that argument and everything else works.

Maybe we can either detect that the supplied jar is free-edition and act accordingly, or at least have a command line flag that suppresses the use of ```--project-file``` argument.

**Comment by gangelino** [comment]
Sure, feel free to submit a PR with this change.
