### ISSUE TITLE
class not found ?

### ISSUE THREAD

**Issue by zhangshuaiqiang-deepexi** [vmware/burp-rest-api#90]
![image](https://user-images.githubusercontent.com/49676213/61615018-a6345f00-ac97-11e9-9f0d-5a4e68540b62.png)

**Comment by adracea** [comment]
Which version of Burp Suite are you trying to use this with ? Keep in mind Burp 2.X will possibly not work

**Comment by ikkisoft** [comment]
Can you post the command line? Are you using the `--burp` flag?

e.g.
```
java -jar burp-rest-api-2.0.0.jar --headless.mode=false --burp.jar=./lib/burpsuite_pro.jar
```

**Comment by zhangshuaiqiang-deepexi** [comment]
![image](https://user-images.githubusercontent.com/49676213/61629562-dab81300-acb7-11e9-8f23-271fbbe51954.png)
 where  is  the  jarfile ? ,i have not.

**Comment by ikkisoft** [comment]
That's the official Burp Professional jar - https://portswigger.net/burp
