### ISSUE TITLE
Project option configuration not working properly

### ISSUE THREAD

**Issue by monyonk** [vmware/burp-rest-api#92]
**Describe the bug**
The project option configuration not loaded by burpsuite, so burpsuite started with it's default configuration. 

**To Reproduce**
1. Start burpsuite as usually 
`java -jar burp-rest-api-2.0.1.jar --headless.mode=false --burp.jar=/opt/BurpSuitePro/burpsuite_pro.jar`

with default configuration from https://github.com/vmware/burp-rest-api/blob/master/src/main/resources/static/burp-default-project-options.json that will turn on all scan type

```
 "scan_issues":{
            "scan_type_intrusive_active":true, <==
            "scan_type_light_active":true, <==
            "scan_type_medium_active":true, <==
            "scan_type_passive":true, <==
            "scan_type_static_code_analysis":true, <==
            "select_individual_issues":false,
            "selected_issues":[]
        }
```

2. Click settings on live audit task
3. Go to Scan configuration, and edit Current auditing configuration to view
4. And we can see the current configuration not like our above configuration that turn on all scan type

![Screenshot from 2019-08-11 20-23-41](https://user-images.githubusercontent.com/20598139/62837152-40376800-bc96-11e9-8d85-51fac033b794.png)

**Expected behavior**
I expect all scan type configuration to be actived when burpsuite was started, like pict bellow

![Screenshot from 2019-08-12 00-05-01](https://user-images.githubusercontent.com/20598139/62837193-e08d8c80-bc96-11e9-8e26-72ec59e65da7.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Burp Suite _Professional_2.1.02
 - Extension 2.0.1 version 

**Additional context**
I have try to replace "scan_issues" to "issues_reported", still fail

**Comment by thypon** [comment]
I tried replicating the bug. Unfortunately it seems to be a bug/feature of newer burp suite > `2.x`. There does not seem to be a way to specify how the live scanner works from project option configuration.

**Comment by ikkisoft** [comment]
I've discovered a feature request on Burp's website, confirming what @thypon mentioned.

https://forum.portswigger.net/thread/scan-configuration-80c07e6d3e1080058

If you're interested in having this feature, please comment on the Burp Suite Forum since we cannot really do anything, unless the functionality is exported by Burp itself.

**Comment by dinvlad** [comment]
FWIW we aren't able to do it with `1.7.22` - I tried both `scan_issues` and `issues_reported` and neither gets applied, it seems. Is there any workaround?
