### ISSUE TITLE
[Enhancement] Support Java x64 version 11

### ISSUE THREAD

**Issue by EasyNV** [vmware/burp-rest-api#94]
Are there any future development to make this tool support Java x64 version 11 and higher? Thank you in advance

**Comment by ikkisoft** [comment]
Can you specify the issues you're having using such JVM release?

**Comment by EasyNV** [comment]
Just for enhancement, because the latest installable version of Burp Suite (2020.1) comes bundled with OpenJDK Version 12.0.2.

As for spesific issues  that  I found is the same as  #95, maybe it's related?

Best Regards and Thank you in advance! 🙏

**Comment by ikkisoft** [comment]
We've sponsored a two days bug squash, and finally fixed the incompatibility with recent versions of Java. For recent JVMs, you have to use the `burp-rest-api.sh` script to start the extension.

![image](https://user-images.githubusercontent.com/6027823/79209785-2614e180-7e44-11ea-84a0-04b282d7a0d6.png)

**Comment by EasyNV** [comment]
Thank you very much @ikkisoft and team!
