### ISSUE TITLE
The /burp/scanner/status API still returns "scanPercentage": 0 after the scans are complete

### ISSUE THREAD

**Issue by sujendram** [vmware/burp-rest-api#95]
**Describe the bug**
The /burp/scanner/status API still returns "scanPercentage": 0 after the scans are complete

**To Reproduce**
1. Use the "/burp/scanner/scans/active" API to trigger the scan on target url
2. Check the UI to see if the scans are finished 
3. Once the active scan and passive scan is complete, use the "/burp/scanner/status" api
4. The response from status API is still "scanPercentage": 0

**Expected behavior**
The scan status API should return "scanPercentage": 100

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Burp Suite _Professional_  v2020.2
 - Extension **burp-rest-api** 2.0.1

**Additional context**

**Comment by sujendram** [comment]
Adding screenshots
![burp_scans_screenshot](https://user-images.githubusercontent.com/58481804/77420054-61953080-6def-11ea-8165-5a27bec0478d.JPG)
![burp_api_screenshot](https://user-images.githubusercontent.com/58481804/77420068-6a860200-6def-11ea-90a8-c58e6f2bf689.JPG)

**Comment by ikkisoft** [comment]
This looks like a bug. We're not actively supporting this extension at this time, but will try to take a look at some point

**Comment by ikkisoft** [comment]
`getPercentageComplete()` in _IScanQueueItem_ has been deprecated by Burp Suite.

We've pushed a change to simulate the 100% once the scan is either canceled, finished or abandoned. This should at least avoid breaks in CI/CD pipelines.
